name: run tests
on:
  workflow_call:
    inputs:
      deploy-env:
        description: Deploy environment to install to
        required: true
        type: string
    secrets:
      DEPLOY_PAT:
        required: true

jobs:
  run-tests:
    runs-on: [self-hosted, deployer]
    defaults:
      run:
        working-directory: system-tests/
    steps:
      - uses: actions/checkout@v2
        with:
          repository: inception-health/patientx
          token: ${{ secrets.DEPLOY_PAT }}  
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://npm.pkg.github.com"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.DEPLOY_PAT }}
      - run: npm ci
      - run: >
          DEPLOY_ENV=${{ inputs.deploy-env }}
          npm run test
