name: install
on:
  workflow_call:
    inputs:
      deploy-env:
        description: Deploy environment to install to
        required: true
        type: string
      installer-repository-name:
        description: Repository name to use to install
        required: true
        type: string
      app-version:
        description: App version to install
        required: false
        type: string
      function-version:
        description: Function version to install
        required: false
        type: string

jobs:
  install:
    runs-on: [self-hosted, deployer]
    steps:
      - name: Amazon ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Install
        run: >
          docker run 
          --rm
          -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
          -e AWS_REGION=$AWS_REGION
          -e AWS_ROLE_ARN=$AWS_ROLE_ARN
          -e AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE
          -v $AWS_WEB_IDENTITY_TOKEN_FILE:$AWS_WEB_IDENTITY_TOKEN_FILE
          -e DEPLOY_ENV=${{ inputs.deploy-env }}
          -e NODE_ENV=production
          -e APP_VERSION=${{ inputs.app-version }}
          -e FUNCTION_VERSION=${{ inputs.function-version }}
          $ECR_REGISTRY/${{ inputs.installer-repository-name }}
          npm run deploy
