name: handle build completed

on:
  workflow_call:
    inputs:
      payloadJSON:
        description: The payload as a JSON string.
        required: true
        type: string
    secrets:
      token:
        required: true

concurrency: handle-build-completed

jobs:
  replace-version:
    runs-on: [self-hosted, deployer]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.repository.default_branch }} # By default, checkout is using the ref of when the event was created. This will minimize merge conflict
          token: ${{ secrets.token }}
      - run: touch '${{ fromJSON(inputs.payloadJSON).service_name }}.config.yml'
      - name: Replace version
        run: yq eval -i '.${{ fromJSON(inputs.payloadJSON).artifact_type }}-version = "${{ fromJSON(inputs.payloadJSON).artifact_version }}"' '${{ fromJSON(inputs.payloadJSON).service_name }}.config.yml'
      - name: Set SHORT_SHA env var
        run: echo "SHORT_SHA=$(echo ${{ fromJSON(inputs.payloadJSON).artifact_version }} | cut -c1-7)" >> $GITHUB_ENV
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: |
            feat(${{ fromJSON(inputs.payloadJSON).artifact_type }}/${{ fromJSON(inputs.payloadJSON).service_name }}): set version to ${{ env.SHORT_SHA }}
            triggered commit: ${{ github.server_url }}/${{ fromJSON(inputs.payloadJSON).source_repo }}/commit/${{ fromJSON(inputs.payloadJSON).artifact_version }}
          commit_author: ${{ fromJSON(inputs.payloadJSON).author }}>
          skip_dirty_check: false
