name: "pr-check"

on:
  workflow_call:
    inputs:
      service-name:
        description: Name of the node service
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: [self-hosted, builder]
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Amazon ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}/${{ inputs.service-name }}-infra
          tags: type=sha,format=long,prefix=
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: infra/${{ inputs.service-name }}
          push: true
          cache-from: type=gha,scope=${{ github.event.repository.name }}-${{ inputs.service-name }}-infra
          cache-to: type=gha,scope=${{ github.event.repository.name }}-${{ inputs.service-name }}-infra,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NODE_AUTH_TOKEN=${{ secrets.token }}
  test: # unit tests can intermittently fail. splitting out allows re-running without failing when trying to push docker image on same sha
    needs: build
    runs-on: [self-hosted, builder]
    timeout-minutes: 10
    steps:
      - name: Amazon ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Run unit test
        run: >
          docker run
          --rm
          ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}/${{ inputs.service-name }}-infra:${{ github.sha }}
          npm run test:ci
  synth:
    needs: build
    runs-on: [self-hosted, builder]
    timeout-minutes: 4
    strategy:
      matrix:
        deploy-env: [dev, staging, production]
      fail-fast: false
    steps:
      - name: Amazon ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: synth
        run: >
          docker run
          --rm
          -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
          -e AWS_REGION=$AWS_REGION
          -e AWS_ROLE_ARN=$AWS_ROLE_ARN
          -e AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE
          -v $AWS_WEB_IDENTITY_TOKEN_FILE:$AWS_WEB_IDENTITY_TOKEN_FILE
          -e DEPLOY_ENV=${{ matrix.deploy-env }}
          -e APP_VERSION="DUMMY_VERSION_FOR_SYNTH"
          ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}/${{ inputs.service-name }}-infra:${{ github.sha }}
          npm run synth
