name: "pr-check"

on:
  workflow_call:
    inputs:
      service-name:
        description: Name of the node service
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: [self-hosted, builder]
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Amazon ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}/${{ inputs.service-name }}
          tags: type=sha,format=long,prefix=
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: services/${{ inputs.service-name }}
          push: true
          cache-from: type=gha,scope=${{ github.event.repository.name }}-${{ inputs.service-name }}
          cache-to: type=gha,scope=${{ github.event.repository.name }}-${{ inputs.service-name }},mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NODE_AUTH_TOKEN=${{ secrets.token }}
  test: # unit tests can intermittently fail. splitting out allows re-running without failing when trying to push docker image on same sha
    needs: build
    runs-on: [self-hosted, builder]
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and load target base
        uses: docker/build-push-action@v2
        with:
          context: services/${{ inputs.service-name }}
          load: true
          cache-from: type=gha,scope=${{ github.event.repository.name }}-${{ inputs.service-name }}
          tags: base:${{ github.sha }}
          target: base
          build-args: |
            NODE_AUTH_TOKEN=${{ secrets.token }}
      - name: Run unit test
        run: >
          docker run
          --rm
          base:${{ github.sha }}
          npm run test:ci
      - name: Check dependencies
        if: always()
        run: >
          docker run
          --rm
          base:${{ github.sha }}
          npm run check-dependencies
