name: build

on:
  workflow_call:
    inputs:
      service-name:
        description: Name of the node service
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  build-and-push:
    runs-on: [self-hosted, builder]
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Amazon ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}/${{ inputs.service-name }}-infra
          tags: type=sha,format=long,prefix=
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: infra/${{ inputs.service-name }}
          push: true
          # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#local-cache
          cache-from: type=local,src=/tmp/.buildx-cache/${{ github.event.repository.name }}-${{ inputs.service-name }}-infra
          cache-to: type=local,dest=/tmp/.buildx-cache/${{ github.event.repository.name }}-${{ inputs.service-name }}-infra-new,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NODE_AUTH_TOKEN=${{ secrets.token }}
      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache/${{ github.event.repository.name }}-${{ inputs.service-name }}-infra
          mv /tmp/.buildx-cache/${{ github.event.repository.name }}-${{ inputs.service-name }}-infra-new /tmp/.buildx-cache/${{ github.event.repository.name }}-${{ inputs.service-name }}-infra
